import type { ReactNode } from "react";

import {
  IconClipboardList,
  IconCog,
  IconCoins,
  IconDashboard,
  IconFactory,
  IconMessageCircle,
  IconShoppingCart,
  IconTag,
  IconTruck,
  IconUser,
  IconUsers,
  IconWrench,
} from "../icons/Icons";

export const NAV: Array<{ id: string | null; label: string; icon: ReactNode; group: string | null }> = [
  { id: "dashboard", label: "Dashboard", icon: <IconDashboard size={18} />, group: null },
  { id: null, label: "ADMIN TASKS", icon: null, group: "header" },
  { id: "users", label: "Manage User Profiles", icon: <IconUser size={18} />, group: "admin" },
  { id: "engineer-assignment-management", label: "Engineer Assignment Management", icon: <IconClipboardList size={18} />, group: "admin" },
  { id: "sales-assignment-management", label: "Sales Assignment Management", icon: <IconUsers size={18} />, group: "admin" },
  { id: "role-management", label: "Role Management", icon: <IconCog size={18} />, group: "admin" },
  { id: "customers", label: "Manage Customers", icon: <IconUsers size={18} />, group: "admin" },
  { id: "price-input", label: "Price Input Module", icon: <IconCoins size={18} />, group: "admin" },
  { id: null, label: "INVENTORY", icon: null, group: "header" },
  { id: "serials", label: "Serial Management", icon: <IconTag size={18} />, group: "inventory" },
  { id: "products", label: "Manage Products", icon: <IconClipboardList size={18} />, group: "inventory" },
  { id: "series-bom", label: "Series BOM Master", icon: <IconClipboardList size={18} />, group: "inventory" },
  { id: "rawmaterials", label: "Manage Raw Materials", icon: <IconWrench size={18} />, group: "inventory" },
  { id: "manufactured", label: "Manufactured Products", icon: <IconCog size={18} />, group: "inventory" },
  { id: "faulty-returns", label: "Faulty & Repaired Tracking", icon: <IconWrench size={18} />, group: "inventory" },
  { id: null, label: "SALES", icon: null, group: "header" },
  { id: "sales-distributor", label: "Distributor Registration", icon: <IconCoins size={18} />, group: "sales" },
  { id: "sales-pi", label: "PI", icon: <IconCoins size={18} />, group: "sales" },
  { id: "sales-dispatch", label: "Dispatch Request", icon: <IconTruck size={18} />, group: "sales" },
  // { id: "sales-tax", label: "Accounts Docs", icon: <IconClipboardList size={18} />, group: "sales" },
  { id: null, label: "DISPATCH", icon: null, group: "header" },
  { id: "inventory-sales-entry", label: "Sales Record", icon: <IconShoppingCart size={18} />, group: "dispatch" },
  { id: "dispatch-team", label: "Dispatch Team", icon: <IconTruck size={18} />, group: "dispatch" },
  { id: null, label: "ACCOUNTS", icon: null, group: "header" },
  { id: "accounts-team", label: "Accounts Team", icon: <IconClipboardList size={18} />, group: "accounts" },
  { id: null, label: "COMPLAINTS", icon: null, group: "header" },
  { id: "complaints-consumer", label: "Complaints: Consumer", icon: <IconMessageCircle size={18} />, group: "complaints" },
  { id: "complaints-supplier", label: "Complaints: Supplier", icon: <IconFactory size={18} />, group: "complaints" },
  { id: null, label: "DISTRIBUTORS", icon: null, group: "header" },
  { id: "distributors", label: "Distributors Detail", icon: <IconTruck size={18} />, group: "distributors" },
];
