import bcrypt from "bcryptjs";

import type {
  Complaint,
  Customer,
  Distributor,
  ManufacturedProduct,
  Product,
  RawMaterial,
  PendingRegistration,
  Sale,
  SerialEntry,
  User,
  UserRole,
} from "../types";

// NOTE: In production, replace these arrays with actual DB calls (Prisma/Postgres/etc).
export const db = {
  users: [
    {
      id: "u-oddo-superadmin",
      email: "superadmin@oddo.com",
      passwordHash: bcrypt.hashSync("ODDO@123", 10),
      name: "Super Admin",
      mobile: "9999999991",
      role: "Admin" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-oddo-admin",
      email: "admin@oddo.com",
      passwordHash: bcrypt.hashSync("ODDO@123", 10),
      name: "Admin User",
      mobile: "9999999992",
      role: "Admin" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-oddo-manager",
      email: "manager@oddo.com",
      passwordHash: bcrypt.hashSync("ODDO@123", 10),
      name: "Manager User",
      mobile: "9999999994",
      role: "Sales Manager" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-oddo-tl",
      email: "tl@oddo.com",
      passwordHash: bcrypt.hashSync("ODDO@123", 10),
      name: "Team Lead",
      mobile: "9999999995",
      role: "L2 Technical Team" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-oddo-itservice",
      email: "itservice@oddo.com",
      passwordHash: bcrypt.hashSync("ODDO@123", 10),
      name: "IT Service",
      mobile: "9999999996",
      role: "Service" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-oddo-employee",
      email: "employee@oddo.com",
      passwordHash: bcrypt.hashSync("ODDO@123", 10),
      name: "Employee User",
      mobile: "9999999993",
      role: "Dealer" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u3",
      email: "sales@avavbusiness.com",
      passwordHash: bcrypt.hashSync("Sales@123", 10),
      name: "Sales Manager",
      mobile: "9380482094",
      role: "Sales Manager" as UserRole,
      isActive: true,
      assignedStates: ["UP"],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-l1-piyush-bhaskar",
      email: "piyushbhaskar343@gmail.com",
      passwordHash: bcrypt.hashSync("PiyushBhaskarL1@123", 10),
      name: "Piyush Bhaskar",
      mobile: "9289960486",
      role: "L1 Engineer" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-l1-neeraj-prajapati",
      email: "neerajkumarprajapatin187@gmail.com",
      passwordHash: bcrypt.hashSync("NeerajPrajapatiL1@123", 10),
      name: "Neeraj Kumar Prajapati",
      mobile: "7052638827",
      role: "L1 Engineer" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-l1-akhil",
      email: "akhilchaubey2005@gmail.com",
      passwordHash: bcrypt.hashSync("AkhilL1@123", 10),
      name: "Akhil Chaubey",
      mobile: "7068571905",
      role: "L1 Engineer" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-l1-sumit",
      email: "sumit9315716457@gmail.com",
      passwordHash: bcrypt.hashSync("SumitKumarL1@123", 10),
      name: "Sumit Kumar",
      mobile: "9289960482",
      role: "L1 Engineer" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-l2-prashant-patel",
      email: "nidhipatel45354@gmail.com",
      passwordHash: bcrypt.hashSync("PrashantPatelL2@123", 10),
      name: "Prashant Kumar Patel",
      mobile: "6260663533",
      role: "L2 Technical Team" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-l2-naveen-maurya",
      email: "naveenmaurya7705@gmail.com",
      passwordHash: bcrypt.hashSync("NaveenMauryaL2@123", 10),
      name: "Naveen Maurya",
      mobile: "9289960484",
      role: "L2 Technical Team" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-l1-aashutosh",
      email: "aashutoshkushwaha95499@gmail.com",
      passwordHash: bcrypt.hashSync("AashutoshL1@123", 10),
      name: "Aashutosh Kushwaha",
      mobile: "9289960485",
      role: "L1 Engineer" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-l1-neeraj-dhiman",
      email: "dhimanneeraj330@gmail.com",
      passwordHash: bcrypt.hashSync("NeerajDhimanL1@123", 10),
      name: "Neeraj Kumar Dhiman",
      mobile: "9217353144",
      role: "L1 Engineer" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-l1-rajat",
      email: "rajat96906387@gmail.com",
      passwordHash: bcrypt.hashSync("RajatL1@123", 10),
      name: "Rajat Singh Chauhan",
      mobile: "7351041998",
      role: "L1 Engineer" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-l1-prashant-singh",
      email: "singhprashant70604@gmail.com",
      passwordHash: bcrypt.hashSync("PrashantSinghL1@123", 10),
      name: "Prashant Singh",
      mobile: "8858203510",
      role: "L1 Engineer" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-l1-swastik",
      email: "swastikupadhyay106@gmail.com",
      passwordHash: bcrypt.hashSync("SwastikL1@123", 10),
      name: "Swastik Upadhyay",
      mobile: "9905774251",
      role: "L1 Engineer" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-l1-nitin",
      email: "rohillanitin123321@gmail.com",
      passwordHash: bcrypt.hashSync("NitinL1@123", 10),
      name: "Nitin Rohilla",
      mobile: "9817887630",
      role: "L1 Engineer" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-l3-ankit",
      email: "service@avavbusiness.com",
      passwordHash: bcrypt.hashSync("AnkitPremiL3@123", 10),
      name: "Ankit Premi",
      mobile: "9289960490",
      role: "L3 Advanced OEM Support" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-admin-ansh",
      email: "ansh@avavbusiness.com",
      passwordHash: bcrypt.hashSync("AnshAdmin@123", 10),
      name: "Ansh Yadav",
      mobile: "9380482094",
      role: "Admin" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-admin-vivek",
      email: "vivek@avavbusiness.com",
      passwordHash: bcrypt.hashSync("VivekAdmin@123", 10),
      name: "Vivek Dutt",
      mobile: "9871125102",
      role: "Admin" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-admin-rohit",
      email: "rohit@avavbusiness.com",
      passwordHash: bcrypt.hashSync("RohitAdmin@123", 10),
      name: "Rohit Jain",
      mobile: "9953840062",
      role: "Admin" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-accounts-rajesh",
      email: "accounts@avavbusiness.com",
      passwordHash: bcrypt.hashSync("RajeshAccounts@123", 10),
      name: "Rajesh Kumar Jha",
      mobile: "9289968570",
      role: "Accounts" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-dispatch-lokesh",
      email: "dispatch@avavbusiness.com",
      passwordHash: bcrypt.hashSync("LokeshDispatch@123", 10),
      name: "Lokesh Kumar",
      mobile: "9718557651",
      role: "Dispatch" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ] as User[],

  pendingRegistrations: [] as PendingRegistration[],

  customers: [
    {
      id: "c1",
      name: "MAA VINDHYAVASINI ENTERPRISES",
      type: "Distributor" as const,
      email: "maavindhyavasini@default.com",
      phone: "0000000000",
      status: "Active" as const,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "c2",
      name: "GARHWAL SOLAR SOLUTION",
      type: "Individual" as const,
      email: "garhwalsolar@default.com",
      phone: "0000000000",
      status: "Active" as const,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ] as Customer[],

  products: [
    {
      id: "p1",
      series: "AURAWATT LFP SERIES(12.4KW/240V/52AH)",
      model: "AW-LFP-240-52",
      createdAt: new Date(),
    },
    { id: "p2", series: "AURAWATT LFP SERIES(25.6V/100AH)", model: "AW-LFP-25.6", createdAt: new Date() },
    { id: "p3", series: "AURAWATT LFP SERIES(48V/60AH)", model: "AW-LFP-48-60", createdAt: new Date() },
    { id: "p4", series: "AURAWATT LFP SERIES(48V/70AH)", model: "AW-LFP-48-70", createdAt: new Date() },
    { id: "p5", series: "AURAWATT LFP SERIES(51.2V/100AH)", model: "AW-LFP-51.2", createdAt: new Date() },
    { id: "p6", series: "SP SERIES (3-6 KW / 48V / IP66)", model: "AW-SP-3000", hsnSac: "8504", gstRate: 5, dealerPrice: 120, distributorPrice: 100, createdAt: new Date() },
    { id: "p7", series: "SP SERIES (3-6 KW / 48V / IP66)", model: "AW-SP-4000", hsnSac: "8504", gstRate: 5, dealerPrice: 120, distributorPrice: 100, createdAt: new Date() },
    { id: "p8", series: "SP SERIES (3-6 KW / 48V / IP66)", model: "AW-SP-5000", hsnSac: "8504", gstRate: 5, dealerPrice: 240, distributorPrice: 200, createdAt: new Date() },
    { id: "p9", series: "SP SERIES (3-6 KW / 48V / IP66)", model: "AW-SP-6000", hsnSac: "8504", gstRate: 5, dealerPrice: 240, distributorPrice: 200, createdAt: new Date() },
    { id: "p10", series: "SP SERIES (5-11 KW / 48V / IP21)", model: "AW-SP-10000", hsnSac: "8504", gstRate: 5, dealerPrice: 240, distributorPrice: 200, createdAt: new Date() },
    { id: "p11", series: "TP-L SERIES", model: "AW-TP-8000-L", createdAt: new Date() },
    { id: "p12", series: "TP-L SERIES", model: "AW-TP-10000-L", createdAt: new Date() },
    {
      id: "p-client-4kw",
      series: "NovaAssets SP Series-",
      model: "(AW-SP-4KW/48V Inverter)",
      hsnSac: "8504",
      gstRate: 5,
      dealerPrice: 120,
      distributorPrice: 100,
      createdAt: new Date(),
    },
    {
      id: "p-client-5kw",
      series: "NovaAssets SP Series-",
      model: "(AW-SP-5KW/48V Inverter)",
      hsnSac: "8504",
      gstRate: 5,
      dealerPrice: 240,
      distributorPrice: 200,
      createdAt: new Date(),
    },
    {
      id: "p-client-10kw",
      series: "NovaAssets SP Series-",
      model: "(AW-SP-10KW/48V Inverter)",
      hsnSac: "8504",
      gstRate: 5,
      dealerPrice: 240,
      distributorPrice: 200,
      createdAt: new Date(),
    },
    {
      id: "p-client-lfp-8504",
      series: "Li-ion (LFP) Battery - AW LVLFP -",
      model: "51.2V/100AH",
      hsnSac: "8504",
      gstRate: 18,
      dealerPrice: 360,
      distributorPrice: 300,
      createdAt: new Date(),
    },
    {
      id: "p-client-lfp-8507",
      series: "Li-ion (LFP) Battery - AW LVLFP -",
      model: "51.2V/100AH (HSN 8507)",
      hsnSac: "8507",
      gstRate: 18,
      dealerPrice: 480,
      distributorPrice: 400,
      createdAt: new Date(),
    },
  ] as Product[],

  rawMaterials: [] as RawMaterial[],
  manufactured: [] as ManufacturedProduct[],
  serials: [] as SerialEntry[],
  sales: [] as Sale[],
  complaints: [] as Complaint[],

  distributors: [
    {
      id: "d1",
      name: "H2 SOLAR POWER PRIVATE LIMITED",
      email: "h2solar08@gmail.com",
      mobile: "9026233630",
      address: "Lucknow, Uttar Pradesh 226201",
      unitsSold: 85,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "d2",
      name: "DVH SOLAR GREEN ENERGY",
      email: "Harshrana1705@gmail.com",
      mobile: "7453040223",
      address: "Saharanpur, Uttar Pradesh",
      unitsSold: 14,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ] as Distributor[],
};
